name: Build and Release Resume

on:
  push:
    paths:
      - 'resume.md'
    branches:
      - main
  workflow_dispatch:
    inputs:
      markdown_content:
        description: '請貼上你的 Markdown 內容'
        required: true
        type: string # 這裡只能是 string

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create MD File from Input
        run: |
          echo "${{ inputs.markdown_content }}" > resume.md

      - name: Convert Markdown to PDF
        run: |
          echo "拉取 Docker映像檔..."
          docker pull ghcr.io/opensource4you/resume:latest
          
          echo "開始轉檔..."
          
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ghcr.io/opensource4you/resume:latest \
            /bin/sh -c "cp /workspace/resume.md /tmp/quarto-resume-template/resume.qmd && quarto render resume.qmd --to pdf && cp /tmp/quarto-resume-template/_site/resume.pdf /workspace/"
          
          echo "檢查 PDF 是否生成..."
          ls -l resume.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
          retention-days: 5

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: resume-${{ github.run_number }}
          name: Resume Build ${{ github.run_number }}
          files: resume.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}